package com.weavetext.ime.core

import android.content.Context
import android.os.Handler
import android.os.Looper
import android.util.Log
import com.weavetext.ime.models.Downloader
import com.weavetext.ime.models.ModelManager
import com.weavetext.ime.models.Progress
import org.json.JSONObject
import java.io.File
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.Executors
import java.util.concurrent.atomic.AtomicBoolean

/** 目录里的一个专业词库。 One domain dictionary in the catalog. */
data class DictPack(
    val id: String, val name: String, val description: String, val license: String, val source: String,
    val words: Int, val bytes: Long, val sha256: String,
)

sealed interface PackState {
    data object NotInstalled : PackState
    data class Downloading(val progress: Progress?) : PackState
    data object Installed : PackState
    data class Failed(val message: String) : PackState
}

/** 界面看到的专业词库操作（截图测试用假实现）。 Domain dictionary operations seen by the UI; faked in tests. */
interface DictPackRepository {
    val packs: List<DictPack>
    fun state(id: String): PackState
    fun install(id: String)
    fun cancel(id: String)
    fun remove(id: String): Boolean
    fun addListener(l: () -> Unit)
    fun removeListener(l: () -> Unit)
}

/**
 * 专业词库：目录随应用（assets/dictpacks.json，由 data/packs.sh 生成），文件从仓库 Release 下载，
 * 经多镜像与 SHA-256 校验后放进 filesDir/dict/packs，立即挂到内核上；删除同样即时生效。
 * Domain dictionaries: the catalog ships with the app (generated by data/packs.sh); files come from the repository's
 * release through the mirrors with SHA-256 checks, land in filesDir/dict/packs and attach to the engine at once;
 * removal takes effect immediately too.
 */
class DictPacks private constructor(private val ctx: Context) : DictPackRepository {
    private val base: String
    override val packs: List<DictPack>

    init {
        val o = runCatching { JSONObject(ctx.assets.open(CATALOG).use { it.readBytes().toString(Charsets.UTF_8) }) }.getOrNull()
        base = o?.optString("base").orEmpty()
        packs = parse(o)
    }

    private val states = ConcurrentHashMap<String, PackState>()
    private val cancels = ConcurrentHashMap<String, AtomicBoolean>()
    private val listeners = ArrayList<() -> Unit>()
    private val io = Executors.newSingleThreadExecutor { r -> Thread(r, "weave-dictpack").apply { isDaemon = true } }
    private val main = Handler(Looper.getMainLooper())

    private fun file(id: String) = File(dir(ctx), "$id.wvz")

    override fun state(id: String): PackState = states[id] ?: if (file(id).isFile) PackState.Installed else PackState.NotInstalled

    private fun set(id: String, s: PackState) {
        states[id] = s
        main.post { synchronized(listeners) { listeners.toList() }.forEach { it() } }
    }

    override fun addListener(l: () -> Unit) { synchronized(listeners) { listeners += l } }
    override fun removeListener(l: () -> Unit) { synchronized(listeners) { listeners -= l } }

    override fun install(id: String) {
        val p = packs.firstOrNull { it.id == id } ?: return
        if (state(id) is PackState.Downloading || base.isEmpty()) return
        val cancel = AtomicBoolean(false)
        cancels[id] = cancel
        set(id, PackState.Downloading(null))
        io.execute {
            try {
                val mirrors = ModelManager.get(ctx).mirrors()
                val tmp = File(ctx.cacheDir, "dictpacks/$id.wvz")
                Downloader(mirrors).download(base + "$id.wvz", p.sha256, tmp, cancel, expectedSize = p.bytes) { pr -> set(id, PackState.Downloading(pr)) }
                val dest = file(id)
                dest.parentFile?.mkdirs()
                if (!tmp.renameTo(dest)) { tmp.copyTo(dest, overwrite = true); tmp.delete() }
                EngineHolder.peek()?.loadPack(id, dest.absolutePath)
                set(id, PackState.Installed)
            } catch (t: Throwable) {
                Log.w(TAG, "pack $id failed", t)
                set(id, if (cancel.get()) PackState.NotInstalled else PackState.Failed("下载失败，请检查网络后重试"))
            } finally {
                cancels.remove(id)
            }
        }
    }

    override fun cancel(id: String) { cancels[id]?.set(true) }

    override fun remove(id: String): Boolean {
        EngineHolder.peek()?.unloadPack(id)
        val ok = !file(id).exists() || file(id).delete()
        set(id, PackState.NotInstalled)
        return ok
    }

    companion object {
        private const val TAG = "WeaveDictPacks"
        const val CATALOG = "dictpacks.json"

        fun dir(ctx: Context) = File(ctx.filesDir, "dict/packs")

        /** 已下载的词库文件（启动内核时一并载入）。 Downloaded pack files, loaded with the engine. */
        fun installedFiles(ctx: Context): List<Pair<String, File>> =
            dir(ctx).listFiles { f -> f.isFile && f.name.endsWith(".wvz") }.orEmpty().sortedBy { it.name }
                .map { it.name.removeSuffix(".wvz") to it }
                .filter { (id, _) -> id.all { c -> c.isLowerCase() || c.isDigit() || c == '-' || c == '_' } }

        internal fun parse(o: JSONObject?): List<DictPack> {
            val a = o?.optJSONArray("packs") ?: return emptyList()
            return (0 until a.length()).mapNotNull { i ->
                val p = a.optJSONObject(i) ?: return@mapNotNull null
                DictPack(
                    p.optString("id"), p.optString("name"), p.optString("description"), p.optString("license"), p.optString("source"),
                    p.optInt("words"), p.optLong("bytes"), p.optString("sha256"),
                ).takeIf { it.id.isNotEmpty() && it.sha256.length == 64 }
            }
        }

        @Volatile private var instance: DictPacks? = null
        fun get(ctx: Context): DictPacks = instance ?: synchronized(this) { instance ?: DictPacks(ctx.applicationContext).also { instance = it } }
    }
}
